### ISSUE TITLE
equation five

### ISSUE THREAD

**Issue by LeoMax-Xiong** [zhenghuatan/rVAD#2]
https://github.com/zhenghuatan/rVAD/blob/60df8ec4d0e34d422acce93e919475cc604287bc/rVADfast_py_2.0/speechproc.py#L167

Hi, teacher Tan,
 I read the paper in the equation five, the sum is divided to (2N+1), but the code has not do that

**Comment by zhenghuatan** [comment]
Thanks for the comment, Honei.

This equation is related to detecting high-energy frames by comparing this value with a threshold. Without dividing (2N+1) implies a relatively larger threshold \alpha. The algorithm is rather insensitive to the change of this threshold, and we have done a set of experiments, which verified this. Re-running experiments on several datasets also shows that the performance difference between with and without this division is very marginal.
