### ISSUE TITLE
Very slow for long audio, optimization possible?

### ISSUE THREAD

**Issue by dmadhitama** [zhenghuatan/rVAD#4]
Hello, nice work for this repo!

I just want to know if this method can be optimized? Because the computation time was really slow when I used quite long duration audio.

Cheers!

**Comment by zhenghuatan** [comment]
Hi, thanks for your interest. 

There are two versions of rVAD, namely rVAD in MATLAB (including rVAD-fast in MATLAB) and rVAD-fast in Python. If you use the MATLAB version, when calling vad.m, you can set opts as 1 for using flatness (i.e. the rVAD-fast option), which is 10+ times faster with slightly reduced accuracy (except that rVAD-fast does not work for white noise). 

You can as well use rVAD-fast in Python, which is the same as rVAD-fast in MATLAB except that the Python version does not include the MSNE/MMSE speech enhancement module. 

You can read our rVAD paper for details.
