### ISSUE TITLE
The function write an empty file

### ISSUE THREAD

**Issue by ghost** [zhenghuatan/rVAD#5]
Thanks for the research and the code, but the result of the vad() function in rVad2 is an empty file. The variable z written to the file contains only 0 and 1, representing speech frames and non-speech frames.

**Comment by zhenghuatan** [comment]
Hi, the VAD result is saved in the 'fvad' file whose name you need to specify, and the file contains 0 and 1 as you mentioned as well. The vad() function itself does return nothing/empty.
