### ISSUE TITLE
realtime vad implememt

### ISSUE THREAD

**Issue by wanglong100** [zhenghuatan/rVAD#7]
Hi, I have read the paper and the reference code. I found that the input  is a wav file for rVad-fast.py. 
I just wonder whether you'd like to implement the same function for audio stream.
Thanks!

**Comment by zhenghuatan** [comment]
Hi, we have just implemented rVAD-fast that takes streaming audio in. Please refer to the code rVAD_fast_stream.py under ../rVADfast_py_2.0/. 

The code continuously records 5s streaming audio from microphone, and then generates VAD transcriptions and audio which are saved in different files.  Repeat the process again and again until it is terminated by pressing ctl+c. The duration can be changed inside the code.
